# Generated by Django 6.0.1 on 2026-01-31 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_premium', models.BooleanField(default=False)),
                ('section_type', models.CharField(choices=[('TB', 'ThinkBell'), ('NB', 'NewsBytes'), ('QC', 'Quiz Club')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MCQQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('option_a', models.CharField(max_length=200)),
                ('option_b', models.CharField(max_length=200)),
                ('option_c', models.CharField(max_length=200)),
                ('option_d', models.CharField(max_length=200)),
                ('correct_option', models.CharField(max_length=1)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_questions', to='gallop_app.appsection')),
            ],
        ),
        migrations.CreateModel(
            name='SlideQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('expected_answer_keywords', models.TextField(help_text='For Gemini AI analysis')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slide_questions', to='gallop_app.appsection')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='slides/')),
                ('text_content', models.TextField()),
                ('order', models.PositiveIntegerField(default=1)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='gallop_app.slidequestion')),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=50)),
                ('is_premium', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
