# Generated by Django 6.0.1 on 2026-02-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0002_slidequestion_correct_option_slidequestion_option_a_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='score',
            new_name='total_score',
        ),
        migrations.RemoveField(
            model_name='slidequestion',
            name='correct_option',
        ),
        migrations.RemoveField(
            model_name='slidequestion',
            name='option_a',
        ),
        migrations.RemoveField(
            model_name='slidequestion',
            name='option_b',
        ),
        migrations.RemoveField(
            model_name='slidequestion',
            name='option_c',
        ),
        migrations.RemoveField(
            model_name='slidequestion',
            name='option_d',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='category',
        ),
        migrations.AlterField(
            model_name='appsection',
            name='section_type',
            field=models.CharField(choices=[('TB', 'ThinkBell'), ('NB', 'NewsBytes'), ('QC', 'Quiz Club')], max_length=2),
        ),
        migrations.AlterField(
            model_name='slidequestion',
            name='expected_answer_keywords',
            field=models.TextField(blank=True, help_text='Keywords for Gemini AI analysis', null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='mobile',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
