# Generated by Django 6.0.1 on 2026-02-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0003_rename_score_studentprofile_total_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slidequestion',
            name='correct_option',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='slidequestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidequestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidequestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slidequestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
