# Generated by Django 6.0.1 on 2026-02-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0004_slidequestion_correct_option_slidequestion_option_a_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_audience', models.CharField(max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
