# Generated by Django 6.0.1 on 2026-02-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0006_liveevent_quizshow'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='announcements/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(default='All Students', max_length=100),
        ),
    ]
