# Generated by Django 6.0.1 on 2026-02-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0007_remove_announcement_is_active_announcement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizshow',
            name='category',
        ),
        migrations.AddField(
            model_name='quizshow',
            name='youtube_link',
            field=models.URLField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizshow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizshow',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
