# Generated by Django 5.0.1 on 2026-02-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0010_firebasestudentscore_studentmcqresult'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FirebaseStudentScore',
        ),
        migrations.DeleteModel(
            name='StudentMCQResult',
        ),
    ]
