# Generated by Django 5.0.1 on 2026-02-16 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0011_delete_firebasestudentscore_delete_studentmcqresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='is_premium',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='mobile',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='total_score',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='provider',
            field=models.CharField(default='Email', max_length=50),
        ),
    ]
