# Generated by Django 5.0.1 on 2026-02-18 05:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0013_studentprofile_created_at_studentprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='StudentAnswerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(blank=True, max_length=1, null=True)),
                ('descriptive_answer', models.TextField(blank=True, null=True)),
                ('is_correct', models.BooleanField(default=False)),
                ('ai_score', models.IntegerField(default=0)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('news_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallop_app.mcqquestion')),
                ('slide_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallop_app.slidequestion')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallop_app.studentprofile')),
                ('thinkbell_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallop_app.question')),
            ],
        ),
    ]
