# Generated by Django 5.0.1 on 2026-02-19 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0014_studentprofile_total_score_studentanswerrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='target_audience',
            field=models.CharField(blank=True, default='All Students', max_length=100, null=True),
        ),
    ]
