# Generated by Django 5.0.1 on 2026-02-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0015_alter_announcement_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
