# Generated by Django 5.0.1 on 2026-02-24 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0016_studentprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentanswerrecord',
            name='question_slide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gallop_app.questionslide'),
        ),
    ]
