# Generated by Django 5.0.1 on 2026-03-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallop_app', '0017_studentanswerrecord_question_slide'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
    ]
